name: PullRequest Check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: gem install awesome_bot
      - run: pip install json-spec
      - run: awesome_bot --allow=429 contents.json # -w AERecord,theswiftwebdeveloper,bluemix,swiftplayground,awesome-for-swift-cheatsheet
      - run: json validate --schema-file=.github/schema.json --document-file=contents.json